# YOURLS-MCP Configuration

# YOURLS API settings
yourls:
  # URL to your YOURLS API endpoint
  api_url: "https://your-yourls-domain.com/yourls-api.php"
  
  # Authentication details
  username: "your-username"
  password: "your-password"
  
  # Optional: Default domain for shortened URLs (leave empty to use YOURLS default)
  # domain: "https://short.domain"