# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install production dependencies
RUN npm install --production --ignore-scripts

# Copy remaining source
COPY . .

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Copy from builder
COPY --from=builder /app .

# Default command
ENTRYPOINT ["node", "yourls-mcp.js"]
